[scanner]
repeat = true
scan_delay = 60
port_range_start = 25565
port_range_end = 25565
ignore_fake_players = true

[masscan]
# Location of masscans config file
config_file = "masscan.conf"

[database]
host = "postgres.example.com"
port = 5432
table = "postgres"
user = "postgres"
password = "SuperSuperSecretPassword"

[player_tracking]
enabled = false
webhook = "https://discord.com/api/webhooks/blahblahblah"
# Comma separated list of usernames to search for
players = [""]

[country_tracking]
# Enable tracking of country information (requires a valid https://ipinfo.io account token)
enabled = false
# How often to update the country information table in hours (minimum 12 hours)
update_frequency = 48
ipinfo_token = ":3"